services:

  web:
    build:
      context: .
    container_name: web-app
    command: /bin/bash "/app/entrypoint.sh"
    env_file: .env
    ports:
     - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    
  db:
    image: postgres:latest
    container_name: db-app
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis-app

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - web

volumes:
  postgres_data:
